import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Leftbar, Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative min-h-screen flex flex-col w-full bg-slate-950 text-white">
          <Navbar />
          <div className="w-full min-h-[89vh] flex items-center justify-center lg:items-stretch md:items-stretch">
            <div className="w-2/12 hidden lg:block md:block">
              <Leftbar />
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
