import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Leftbar, Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="relative min-h-screen flex flex-col w-full dark:bg-slate-950  dark:text-slate-200 bg-slate-200 text-slate-950">
          {children}
        </main>
      </body>
    </html>
  );
}
