import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative min-h-screen flex flex-col w-full bg-slate-950 text-white">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
